server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:13306/bbb?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root